import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Main() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  interface CardProps {
    title: string;
    content: string;
  }

  const Card: React.FC<CardProps> = ({ title, content }) => {
    return (

      <div className="w-[20rem] min-h-[400px] bg-flower bg-no-repeat bg-cover p-4 text-white mx-auto border border-white rounded-md">
        <p className="text-3xl text-red-700 font-bold text-center"> {title}</p>
        <h1 className="mt-10 text-center text-sm text-green-700"> {content} </h1>
      </div>

    );
  }


  interface Item {
    id: number;
    title: string;
    content: string
  }

  const items: Item[] = [
    { id: 1, title: 'kay', content: 'today' },
    { id: 2, title: 'smith', content: 'now' },
    { id: 3, title: 'paul', content: 'later' },
  ]



  const Home: React.FC = () => {
    return (
      <div className="flex flex-col  px-4 space-y-10 overflow-y-auto max-h-[20rem]">
        {items.map((item) => {

          return <Card key={item.id} title={item.title} content={item.content} />
        })}
      </div>
    )
  }


  return <>  <Head>
    <title>Create T3 App</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <Home />
      </div>


    </main>
  </>

}
